### ISSUE TITLE
Default video container change

### ISSUE THREAD

**Issue by Domino117** [enricobragastini/Panopto-Video-DL#1]
Thank you for making this available.  It is working great but I would like to be able to change the default video codec container to .mp4 rather than .mkv.  I have been able to convert the videos after retrieving from Panopto  but wanted to see if it is possible to skip this step and make .mp4 the default.

I apologize for my lack of experience with coding and ffmpeg and appreciate any help you can offer.

Thank you.

Jon

**Comment by Domino117** [comment]
Don't need to convert after all.  Thanks again for making this available.

**Comment by pizidavi** [comment]
> Thank you for making this available. It is working great but I would like to be able to change the default video codec container to .mp4 rather than .mkv.

Thanks for your feedback! 👋
Try the new version with GUI. There is also the possibility to change the video format!
