### ISSUE TITLE
PanoptoDownloader detected by windows defender as "Trojan:Win32/Wacatac.B!ml"

### ISSUE THREAD

**Issue by superusercode** [enricobragastini/Panopto-Video-DL#2]
![image](https://user-images.githubusercontent.com/60588434/145050325-5fb56681-7617-450a-86aa-e4842fae0109.png)

You can use https://www.microsoft.com/en-us/wdsi/filesubmission in order to remove false flags

**Comment by pizidavi** [comment]
Thanks 👍
